import { useEffect, useMemo, useState } from 'react'
import { format } from 'date-fns'
import { ptBR } from 'date-fns/locale'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Badge } from '@/components/ui/badge'
import { Loader2, CalendarPlus, AlertTriangle, Undo2 } from 'lucide-react'
import useChancellorStore from '@/stores/useChancellorStore'
import useSiteSettingsStore from '@/stores/useSiteSettingsStore'
import useAuthStore from '@/stores/useAuthStore'
import { useToast } from '@/hooks/use-toast'
import { useAsyncOperation } from '@/hooks/use-async-operation'
import type { Event } from '@/lib/data'
import {
  formatGeneratedSessionLabel,
  generateSessionDates,
  getExistingSessionWeekKeys,
  mergeBatchSummariesWithAudit,
  partitionGeneratedSessions,
  summarizeAutoGeneratedBatches,
  type AutoGeneratedBatchSummary,
} from '@/lib/session-generator'
import { resolveEventLocationInput } from '@/lib/event-locations'

interface GenerateSessionsDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const DEFAULT_SESSION_DESCRIPTION =
  'Sessão programada conforme calendário padrão da loja.'

export function GenerateSessionsDialog({
  open,
  onOpenChange,
}: GenerateSessionsDialogProps) {
  const { events, bulkAddEvents, deleteEventsByBatch, registerGenerationBatch, generationBatches } =
    useChancellorStore()
  const { sessionSchedule, siteTitle, contact } = useSiteSettingsStore()
  const { user } = useAuthStore()
  const locations = useChancellorStore((s) => s.locations)
  const { toast } = useToast()

  const generated = useMemo(
    () =>
      generateSessionDates({
        weekday: sessionSchedule.weekday,
        weeksOfMonth: sessionSchedule.weeksOfMonth,
        monthsAhead: sessionSchedule.monthsAhead,
      }),
    [sessionSchedule],
  )

  const existingWeekKeys = useMemo(
    () => getExistingSessionWeekKeys(events),
    [events],
  )
  const { newSessions, conflicts } = useMemo(
    () => partitionGeneratedSessions(generated, existingWeekKeys),
    [generated, existingWeekKeys],
  )

  const autoBatches = useMemo(
    () =>
      mergeBatchSummariesWithAudit(
        summarizeAutoGeneratedBatches(events),
        generationBatches.map((batch) => ({
          id: batch.id,
          createdAt: batch.createdAt,
          createdByName: batch.createdByName,
          sessionsCount: batch.sessionsCount,
          firstDate: batch.firstDate,
          lastDate: batch.lastDate,
        })),
      ),
    [events, generationBatches],
  )

  const [selectedDates, setSelectedDates] = useState<Set<string>>(new Set())
  const [undoingBatchId, setUndoingBatchId] = useState<string | null>(null)
  const [batchToUndo, setBatchToUndo] = useState<AutoGeneratedBatchSummary | null>(
    null,
  )

  useEffect(() => {
    if (open) {
      setSelectedDates(new Set(newSessions.map((session) => session.date)))
    }
  }, [open, newSessions])

  const toggleDate = (date: string, checked: boolean) => {
    setSelectedDates((prev) => {
      const next = new Set(prev)
      if (checked) next.add(date)
      else next.delete(date)
      return next
    })
  }

  const selectAllNew = () => {
    setSelectedDates(new Set(newSessions.map((session) => session.date)))
  }

  const handleUndoBatch = async (batchId: string) => {
    setUndoingBatchId(batchId)
    try {
      const removed = await deleteEventsByBatch(batchId)
      if (removed > 0) {
        toast({
          title: 'Geração desfeita',
          description: `${removed} sessão(ões) removida(s) da agenda.`,
        })
        setBatchToUndo(null)
      } else {
        toast({
          variant: 'destructive',
          title: 'Não foi possível desfazer',
          description: 'Verifique sua conexão e permissões.',
        })
      }
    } finally {
      setUndoingBatchId(null)
    }
  }

  const formatBatchRange = (firstDate: string, lastDate: string) => {
    const fmt = (iso: string) =>
      format(new Date(`${iso}T12:00:00`), 'dd/MM/yyyy', { locale: ptBR })
    return firstDate === lastDate
      ? fmt(firstDate)
      : `${fmt(firstDate)} — ${fmt(lastDate)}`
  }

  const formatBatchAudit = (batch: AutoGeneratedBatchSummary) => {
    if (!batch.generatedAt) return null
    const when = format(new Date(batch.generatedAt), "dd/MM/yyyy 'às' HH:mm", {
      locale: ptBR,
    })
    const who = batch.generatedByName?.trim()
    return who ? `Gerado em ${when} por ${who}` : `Gerado em ${when}`
  }

  const { execute: handleGenerate, loading } = useAsyncOperation(
    async () => {
      const toCreate = newSessions.filter((session) =>
        selectedDates.has(session.date),
      )
      if (toCreate.length === 0) {
        toast({
          variant: 'destructive',
          title: 'Nenhuma sessão selecionada',
          description: 'Marque ao menos uma data para gerar.',
        })
        return
      }

      const resolvedLocation = resolveEventLocationInput({
        locationId: sessionSchedule.defaultLocationId,
        siteTitle,
        contact,
        locations,
      })

      const batchId = crypto.randomUUID()
      const sortedDates = toCreate.map((session) => session.date).sort()
      const batch = await registerGenerationBatch({
        id: batchId,
        createdBy: user?.id,
        sessionsCount: toCreate.length,
        firstDate: sortedDates[0],
        lastDate: sortedDates[sortedDates.length - 1],
      })
      if (!batch) {
        toast({
          variant: 'destructive',
          title: 'Erro ao registrar geração',
          description: 'Não foi possível iniciar o lote de sessões.',
        })
        return
      }

      const payload: Event[] = toCreate.map((session) => ({
        id: crypto.randomUUID(),
        title: sessionSchedule.defaultTitle,
        date: session.date,
        time: sessionSchedule.defaultTime,
        type: 'Sessão',
        location: resolvedLocation.location,
        locationId: resolvedLocation.locationId,
        description: DEFAULT_SESSION_DESCRIPTION,
        attendees: 0,
        isAutoGenerated: true,
        generatedBatchId: batchId,
      }))

      const { created, failed } = await bulkAddEvents(payload)
      if (created.length === 0) {
        await deleteEventsByBatch(batchId)
        toast({
          variant: 'destructive',
          title: 'Erro ao gerar sessões',
          description: 'Não foi possível salvar as sessões. Tente novamente.',
        })
        return
      }

      toast({
        title: 'Sessões geradas',
        description:
          failed > 0
            ? `${created.length} sessão(ões) criada(s). ${failed} falha(s).`
            : `${created.length} sessão(ões) adicionada(s) à agenda.`,
      })
      onOpenChange(false)
    },
    {
      onError: () => {
        toast({
          variant: 'destructive',
          title: 'Erro ao gerar sessões',
          description: 'Verifique sua conexão e permissões.',
        })
      },
    },
  )

  const periodLabel = useMemo(() => {
    if (generated.length === 0) return ''
    const first = generated[0].date
    const last = generated[generated.length - 1].date
    const fmt = (iso: string) =>
      format(new Date(`${iso}T12:00:00`), 'MMM/yyyy', { locale: ptBR })
    return `${fmt(first)} — ${fmt(last)}`
  }, [generated])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <CalendarPlus className="h-5 w-5" />
            Gerar sessões automaticamente
          </DialogTitle>
          <DialogDescription>
            Cria sessões para os próximos {sessionSchedule.monthsAhead} meses com
            base no calendário configurado em Configurações da Loja. Depois você
            pode editar qualquer data individualmente na agenda.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
          <Badge variant="secondary">{periodLabel}</Badge>
          <span>
            {generated.length} data(s) no padrão · {newSessions.length} nova(s) ·{' '}
            {conflicts.length} semana(s) já com sessão
          </span>
        </div>

        {conflicts.length > 0 && (
          <div className="flex items-start gap-2 rounded-md border border-amber-500/40 bg-amber-500/10 p-3 text-sm">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
            <p>
              Semanas que já possuem uma sessão na agenda não serão recriadas
              (mesmo que em outro dia da semana). Edite a sessão existente se
              precisar alterar data, horário ou local.
            </p>
          </div>
        )}

        <div className="flex justify-between items-center">
          <p className="text-sm font-medium">Datas a criar</p>
          <Button type="button" variant="ghost" size="sm" onClick={selectAllNew}>
            Selecionar todas novas
          </Button>
        </div>

        <ScrollArea className="h-[280px] rounded-md border p-2">
          {newSessions.length === 0 ? (
            <p className="p-4 text-center text-sm text-muted-foreground">
              Todas as sessões do período já estão na agenda.
            </p>
          ) : (
            <ul className="space-y-2">
              {newSessions.map((session) => (
                <li
                  key={session.date}
                  className="flex items-center gap-3 rounded-md px-2 py-1.5 hover:bg-muted/50"
                >
                  <Checkbox
                    checked={selectedDates.has(session.date)}
                    onCheckedChange={(checked) =>
                      toggleDate(session.date, checked === true)
                    }
                  />
                  <span className="text-sm">
                    {formatGeneratedSessionLabel(
                      session,
                      sessionSchedule.weekday,
                    )}
                  </span>
                </li>
              ))}
            </ul>
          )}

          {conflicts.length > 0 && (
            <>
              <p className="mt-4 mb-2 text-xs font-medium text-muted-foreground">
                Semana já com sessão (ignoradas)
              </p>
              <ul className="space-y-1 opacity-60">
                {conflicts.map((session) => (
                  <li key={`conflict-${session.date}`} className="px-2 text-sm">
                    {formatGeneratedSessionLabel(
                      session,
                      sessionSchedule.weekday,
                    )}
                  </li>
                ))}
              </ul>
            </>
          )}
        </ScrollArea>

        {autoBatches.length > 0 && (
          <div className="space-y-2 rounded-md border p-3">
            <p className="text-sm font-medium">Gerações anteriores</p>
            <p className="text-xs text-muted-foreground">
              Remova em lote as sessões criadas automaticamente. Sessões editadas
              ou criadas manualmente não são afetadas.
            </p>
            <ul className="space-y-2">
              {autoBatches.map((batch) => (
                <li
                  key={batch.batchId}
                  className="flex items-start justify-between gap-2 text-sm"
                >
                  <div className="min-w-0">
                    <p>
                      {batch.count} sessão(ões) ·{' '}
                      {formatBatchRange(batch.firstDate, batch.lastDate)}
                    </p>
                    {formatBatchAudit(batch) && (
                      <p className="text-xs text-muted-foreground">
                        {formatBatchAudit(batch)}
                      </p>
                    )}
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="shrink-0 text-destructive hover:text-destructive"
                    onClick={() => setBatchToUndo(batch)}
                    disabled={undoingBatchId !== null}
                  >
                    {undoingBatchId === batch.batchId ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Undo2 className="mr-2 h-4 w-4" />
                    )}
                    Desfazer
                  </Button>
                </li>
              ))}
            </ul>
          </div>
        )}

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancelar
          </Button>
          <Button
            type="button"
            onClick={() => handleGenerate()}
            disabled={loading || selectedDates.size === 0}
          >
            {loading ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <CalendarPlus className="mr-2 h-4 w-4" />
            )}
            Gerar {selectedDates.size > 0 ? selectedDates.size : ''} sessão
            {selectedDates.size === 1 ? '' : 'ões'}
          </Button>
        </DialogFooter>
      </DialogContent>

      <AlertDialog
        open={!!batchToUndo}
        onOpenChange={(isOpen) => !isOpen && setBatchToUndo(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Desfazer geração automática?</AlertDialogTitle>
            <AlertDialogDescription>
              {batchToUndo
                ? `Isso removerá ${batchToUndo.count} sessão(ões) do período ${formatBatchRange(batchToUndo.firstDate, batchToUndo.lastDate)}. Sessões criadas ou editadas manualmente não serão afetadas. Esta ação não pode ser desfeita.`
                : ''}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={undoingBatchId !== null}>
              Cancelar
            </AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive hover:bg-destructive/90"
              disabled={undoingBatchId !== null}
              onClick={() => {
                if (batchToUndo) {
                  void handleUndoBatch(batchToUndo.batchId)
                }
              }}
            >
              {undoingBatchId ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Undo2 className="mr-2 h-4 w-4" />
              )}
              Desfazer geração
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Dialog>
  )
}
