import { supabase } from '@/lib/supabase/client'
import { mapBrotherFromDB } from '@/lib/brother-mappers'
import type {
  Event,
  SessionRecord,
  Attendance,
  Brother,
  Location,
} from '@/lib/data'
import { sanitizeLocationIdForDb } from '@/lib/event-locations'
import {
  ATTENDANCE_COLUMNS,
  CHANCELLOR_EVENT_COLUMNS,
  chunkArray,
  getChancellorLookbackSinceIso,
  SESSION_RECORD_COLUMNS,
  SUPABASE_IN_CHUNK_SIZE,
} from '@/lib/chancellor-query-limits'

const LOCATIONS_STORAGE_KEY = 'chancellor_locations'

export function mapEventFromDB(row: Record<string, unknown>): Event {
  const time = row.time
  return {
    id: String(row.id),
    title: String(row.title ?? ''),
    date: String(row.date ?? ''),
    time:
      typeof time === 'string'
        ? time.slice(0, 5)
        : time != null
          ? String(time).slice(0, 5)
          : '00:00',
    type: (row.type as Event['type']) || 'Sessão',
    location: String(row.location ?? ''),
    locationId: row.location_id ? String(row.location_id) : undefined,
    description: String(row.description ?? ''),
    attendees: 0,
    reminders: [],
    timeline: [],
    isAutoGenerated: row.is_auto_generated === true,
    generatedBatchId: row.generated_batch_id
      ? String(row.generated_batch_id)
      : undefined,
  }
}

export function mapSessionRecordFromDB(
  row: Record<string, unknown>,
): SessionRecord {
  return {
    id: String(row.id),
    eventId: String(row.event_id ?? ''),
    date: String(row.date ?? ''),
    charityCollection: Number(row.charity_collection) || 0,
    observations: String(row.observations ?? ''),
    status: (row.status as SessionRecord['status']) || 'Pendente',
  }
}

export function mapAttendanceFromDB(row: Record<string, unknown>): Attendance {
  return {
    id: String(row.id),
    sessionRecordId: String(row.session_record_id ?? ''),
    brotherId: String(row.brother_id ?? ''),
    status: (row.status as Attendance['status']) || 'Ausente',
    justification: row.justification
      ? String(row.justification)
      : undefined,
  }
}

export function loadLocationsFromStorage(): Location[] {
  if (typeof window === 'undefined') return []
  try {
    const raw = localStorage.getItem(LOCATIONS_STORAGE_KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw) as Location[]
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

export function saveLocationsToStorage(locations: Location[]): void {
  if (typeof window === 'undefined') return
  localStorage.setItem(LOCATIONS_STORAGE_KEY, JSON.stringify(locations))
}

function isMissingTable(error: { code?: string; message?: string }): boolean {
  const message = error.message || ''
  return (
    error.code === 'PGRST116' ||
    message.includes('relation') ||
    message.includes('does not exist')
  )
}

export interface ChancellorEventsQueryOptions {
  /** ISO date (YYYY-MM-DD). Padrão: últimos CHANCELLOR_DATA_LOOKBACK_YEARS anos. */
  sinceDate?: string
}

export async function fetchChancellorEvents(
  options?: ChancellorEventsQueryOptions,
): Promise<Event[]> {
  const sinceDate = options?.sinceDate ?? getChancellorLookbackSinceIso()
  const { data, error } = await supabase
    .from('events')
    .select(CHANCELLOR_EVENT_COLUMNS)
    .gte('date', sinceDate)
    .order('date', { ascending: true })

  if (error) {
    if (isMissingTable(error)) return []
    throw error
  }
  return (data ?? []).map((row) => mapEventFromDB(row))
}

export interface ChancellorSessionRecordsQueryOptions {
  sinceDate?: string
}

export async function fetchChancellorSessionRecords(
  options?: ChancellorSessionRecordsQueryOptions,
): Promise<SessionRecord[]> {
  const sinceDate = options?.sinceDate ?? getChancellorLookbackSinceIso()
  const { data, error } = await supabase
    .from('session_records')
    .select(SESSION_RECORD_COLUMNS)
    .gte('date', sinceDate)
    .order('date', { ascending: false })

  if (error) {
    if (isMissingTable(error)) return []
    throw error
  }
  return (data ?? []).map((row) => mapSessionRecordFromDB(row))
}

export interface ChancellorAttendanceQueryOptions {
  sessionRecordIds: string[]
}

export async function fetchChancellorAttendance(
  options: ChancellorAttendanceQueryOptions,
): Promise<Attendance[]> {
  const uniqueIds = [...new Set(options.sessionRecordIds.filter(Boolean))]
  if (uniqueIds.length === 0) return []

  const chunks = chunkArray(uniqueIds, SUPABASE_IN_CHUNK_SIZE)
  const rows: Record<string, unknown>[] = []

  for (const ids of chunks) {
    const { data, error } = await supabase
      .from('attendance')
      .select(ATTENDANCE_COLUMNS)
      .in('session_record_id', ids)

    if (error) {
      if (isMissingTable(error)) return []
      throw error
    }

    if (data?.length) {
      rows.push(...data)
    }
  }

  return rows.map((row) => mapAttendanceFromDB(row))
}

export async function fetchChancellorBrothers(): Promise<Brother[]> {
  const supabaseAny = supabase as any
  const { data, error } = await supabaseAny
    .from('brothers')
    .select('*')
    .order('name', { ascending: true })

  if (error) {
    if (isMissingTable(error)) return []
    throw error
  }
  return (data ?? []).map((row: Record<string, unknown>) => mapBrotherFromDB(row))
}

export function eventToDbPayload(event: Event) {
  return {
    id: event.id,
    title: event.title,
    date: event.date,
    time: event.time,
    type: event.type,
    location: event.location,
    location_id: sanitizeLocationIdForDb(event.locationId),
    description: event.description || '',
    is_auto_generated: event.isAutoGenerated ?? false,
    generated_batch_id: event.generatedBatchId ?? null,
  }
}
