CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logo_url TEXT,
    history_title TEXT DEFAULT 'Tradição e Modernidade',
    history_text TEXT DEFAULT 'Fundada com o propósito de reunir homens livres e de bons costumes, a ARLS Templários da Paz tem sido um pilar de fraternidade em Botucatu. Nossa loja preserva as antigas tradições maçônicas enquanto busca aplicar seus ensinamentos no mundo contemporâneo.' || chr(10) || chr(10) || 'Através do estudo, da reflexão e da prática da beneficência, buscamos construir uma sociedade mais justa e igualitária, começando pela reforma íntima de cada um de nossos membros.',
    history_image_url TEXT DEFAULT 'https://img.usecurling.com/p/800/800?q=old%20books%20library',
    values_liberty TEXT DEFAULT 'Defendemos a liberdade de consciência, de pensamento e de expressão, essenciais para a dignidade humana.',
    values_equality TEXT DEFAULT 'Reconhecemos que todos os homens nascem iguais em direitos e deveres, sem distinção de raça, credo ou condição social.',
    values_fraternity TEXT DEFAULT 'Cultivamos o amor fraternal que une todos os maçons como irmãos, estendendo essa benevolência a toda a humanidade.',
    contact_address TEXT DEFAULT 'Rua das Acácias, 123',
    contact_city TEXT DEFAULT 'Jardim Tropical, Botucatu - SP',
    contact_zip TEXT DEFAULT '18600-000',
    contact_email TEXT DEFAULT 'contato@templariosdapaz.com.br',
    contact_secondary_email TEXT DEFAULT 'secretaria@templariosdapaz.com.br',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.venerables (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    period TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venerables ENABLE ROW LEVEL SECURITY;

-- Policies for site_settings
CREATE POLICY "Allow public read access to site_settings" 
ON public.site_settings FOR SELECT 
USING (true);

CREATE POLICY "Allow authenticated update access to site_settings" 
ON public.site_settings FOR UPDATE 
USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert access to site_settings" 
ON public.site_settings FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- Policies for venerables
CREATE POLICY "Allow public read access to venerables" 
ON public.venerables FOR SELECT 
USING (true);

CREATE POLICY "Allow authenticated all access to venerables" 
ON public.venerables FOR ALL 
USING (auth.role() = 'authenticated');

-- Insert initial settings row if it doesn't exist
INSERT INTO public.site_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Seed some venerables if empty
INSERT INTO public.venerables (name, period, image_url)
SELECT 'Antônio Souza', '2022 - 2024', NULL
WHERE NOT EXISTS (SELECT 1 FROM public.venerables);

INSERT INTO public.venerables (name, period, image_url)
SELECT 'Carlos Ferreira', '2020 - 2022', NULL
WHERE NOT EXISTS (SELECT 1 FROM public.venerables LIMIT 1 OFFSET 1);
